version: '3.8'

networks:
  app_network:

services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      DATABASE_STRING_CONNECTION: mongodb://db:27017/bookstore
    depends_on:
      - db  
    networks:
      - app_network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network
    
volumes:
  mongo-data: